# Generated by Django 5.2.6 on 2025-09-26 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_airport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Airport',
        ),
    ]
